export { default as Layout } from "./Layout";
export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as FwSwiper } from "./FwSwiper";
export { default as Product } from "./Product";
export { default as Category } from "./Category";
export { default as ProductSwiper } from "./ProductSwiper";
export { default as Sugesstion } from "./Sugesstion";
export { default as SpeackerSug } from "./SpeackerSug";
