import { CategoryItem, FwSwiper, ProductSwiper } from "@/components";
import Head from "next/head";
import { SwiperItems } from "@/Datas";
import { Categories } from "@/Datas";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <FwSwiper swiperItems={SwiperItems} />

        <div className="mt-[30px]  w-full flex flex-wrap justify-center gap-[10]  ">
          {Categories.map((category) => (
            <CategoryItem category={category} />
          ))}
        </div>
        <ProductSwiper />
      </div>
    </>
  );
}
